name = "ROK3"
license = "MIT"
licenselink = "https://github.com/robottokauf3/rok3.me/blob/master/themes/rok3/LICENSE.md"
description = "Hugo theme for rok3.me"
homepage = "http://rok3.me"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Robert Kaufmann III"
  homepage = "http://rok3.me"
